ProcessKeyWindow dw LeftWindowKey
LineDrawFunction dw Draw_ChooseLine
WindowFunctions dw LeftWindowKey,DriveWindowKey,RightWindowKey
DrawFunctions dw Draw_ChooseLine,Draw_ChooseDrive,Draw_PlaylistLine
CurrentWindow db 0