ProcessKeyWindow dw LeftWindowKey
LineDrawFunction dw DrawChooseLine
WindowFunctions dw LeftWindowKey,DriveWindowKey,RightWindowKey
DrawFunctions dw DrawChooseLine,DrawChooseDrive,DrawPlaylistLine
CurrentWindow db 0